# Generated by Django 4.1 on 2022-10-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_pendingdeposit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingdeposit',
            name='beratSampah',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pendingdeposit',
            name='poin',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pendingdeposit',
            name='totalHarga',
            field=models.BigIntegerField(),
        ),
    ]
