# Generated by Django 4.1 on 2022-10-27 05:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposit', '0005_delete_pendingdeposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('username', models.TextField(default='')),
                ('jenisSampah', models.TextField()),
                ('beratSampah', models.BigIntegerField()),
                ('poin', models.BigIntegerField()),
                ('totalHarga', models.BigIntegerField()),
                ('isApprove', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
