# Generated by Django 4.1 on 2022-10-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0003_alter_deposit_beratsampah_alter_deposit_poin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
