# Generated by Django 4.1 on 2022-10-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0004_deposit_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='isApprove',
            field=models.TextField(default='APPROVED'),
        ),
    ]
