# Generated by Django 4.1 on 2022-10-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0005_alter_withdraw_isapprove'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
