# Generated by Django 4.1 on 2022-12-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0008_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.TextField(default=''),
        ),
    ]
