# Generated by Django 4.1 on 2022-10-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimoni',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
