# Generated by Django 4.1 on 2022-10-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0002_pendingwithdraw_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingwithdraw',
            name='jumlah',
            field=models.BigIntegerField(),
        ),
    ]
