# Generated by Django 4.1 on 2022-12-02 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0004_withdraw_delete_pendingwithdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 2, 16, 14, 29, 867567)),
        ),
    ]
